package com.qepms.infra.dto.armg;
// default package
// Generated Mar 13, 2014 3:13:19 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Resume generated by hbm2java
 */
public class ResumeDTO implements java.io.Serializable {

	private Integer resumeid;
	private EmployeeMasterDTO employeeMaster;
	private String totalExperience;
	private String relevantExperience;
	private String professionalSummary;
	private String employeeSumbissionStatus;
	private String managerApprovalStatus;
	private Date createdDate;
	private Date updatedDate;
	private String comments;
	private List<ProjectDTO> projects = new ArrayList<ProjectDTO>();
	private List<EducationDTO> educations = new ArrayList<EducationDTO>();
	private List<SkillDTO> skills = new ArrayList<SkillDTO>();
	
	
	/*
	 * custom date
	 */
	private String customCreatedDate;
	private String customUpdatedDate;
	
	/*
	 * To know if its drafted or submitted
	 */
	private String submissionStatus;
	

	public ResumeDTO() {
	}

	public ResumeDTO(Date createdDate, Date updatedDate) {
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	


	public ResumeDTO(Integer resumeid, EmployeeMasterDTO employeeMaster,
			String totalExperience, String relevantExperience,
			String professionalSummary, String employeeSumbissionStatus,
			String managerApprovalStatus, Date createdDate, Date updatedDate,
			String comments, List<ProjectDTO> projects,
			List<EducationDTO> educations, List<SkillDTO> skills,
			String submissionStatus) {
		super();
		this.resumeid = resumeid;
		this.employeeMaster = employeeMaster;
		this.setTotalExperience(totalExperience);
		this.setRelevantExperience(relevantExperience);
		this.professionalSummary = professionalSummary;
		this.employeeSumbissionStatus = employeeSumbissionStatus;
		this.managerApprovalStatus = managerApprovalStatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.comments = comments;
		this.projects = projects;
		this.educations = educations;
		this.skills = skills;
		this.submissionStatus = submissionStatus;
	}

	public Integer getResumeid() {
		return this.resumeid;
	}

	public void setResumeid(Integer resumeid) {
		this.resumeid = resumeid;
	}

	public EmployeeMasterDTO getEmployeeMaster() {
		return this.employeeMaster;
	}

	public void setEmployeeMaster(EmployeeMasterDTO employeeMaster) {
		this.employeeMaster = employeeMaster;
	}

	

	public String getProfessionalSummary() {
		return this.professionalSummary;
	}

	public void setProfessionalSummary(String professionalSummary) {
		this.professionalSummary = professionalSummary;
	}

	public String getEmployeeSumbissionStatus() {
		return this.employeeSumbissionStatus;
	}

	public void setEmployeeSumbissionStatus(String employeeSumbissionStatus) {
		this.employeeSumbissionStatus = employeeSumbissionStatus;
	}

	public String getManagerApprovalStatus() {
		return this.managerApprovalStatus;
	}

	public void setManagerApprovalStatus(String managerApprovalStatus) {
		this.managerApprovalStatus = managerApprovalStatus;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public List<ProjectDTO> getProjects() {
		return projects;
	}

	public void setProjects(List<ProjectDTO> projects) {
		this.projects = projects;
	}

	public List<EducationDTO> getEducations() {
		return educations;
	}

	public void setEducations(List<EducationDTO> educations) {
		this.educations = educations;
	}

	public List<SkillDTO> getSkills() {
		return skills;
	}

	public void setSkills(List<SkillDTO> skills) {
		this.skills = skills;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getSubmissionStatus() {
		return submissionStatus;
	}

	public void setSubmissionStatus(String submissionStatus) {
		this.submissionStatus = submissionStatus;
	}

	public String getTotalExperience() {
		return totalExperience;
	}

	public void setTotalExperience(String totalExperience) {
		this.totalExperience = totalExperience;
	}

	public String getRelevantExperience() {
		return relevantExperience;
	}

	public void setRelevantExperience(String relevantExperience) {
		this.relevantExperience = relevantExperience;
	}

	public String getCustomCreatedDate() {
		return customCreatedDate;
	}

	public void setCustomCreatedDate(String customCreatedDate) {
		this.customCreatedDate = customCreatedDate;
	}

	public String getCustomUpdatedDate() {
		return customUpdatedDate;
	}

	public void setCustomUpdatedDate(String customUpdatedDate) {
		this.customUpdatedDate = customUpdatedDate;
	}

	

	
}
